version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata1:/usr/share/elasticsearch/data

  app:
    image: xmagazine:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
    volumes:
      - ./src/main/resources/application.properties:/app/application.properties
    depends_on:
      - elasticsearch
    # switch this command
    # command: >
    #   sh -c "
    #   java -jar app.jar
    #   "
    # switch this command
    command: >
      sh -c "
      java -cp app.jar com.ssafy.xmagazine.DistanceIndexing &&
      java -cp app.jar com.ssafy.xmagazine.SearchIndexing &&
      java -jar app.jar
      "

volumes:
  esdata1:
    driver: local
